// Generated by CoffeeScript 1.6.1

exports.description = "Template for my Webkit-only pages";

exports.notes = "run `npm install` and `bower install`";

exports.warnOn = '*';

exports.template = function(grunt, init, done) {
  return init.process({}, [], function(err, props) {
    var files, key;
    files = init.filesToCopy(props);
    for (key in files) {
      if (key.match(/^components\//)) {
        delete files[key];
      }
      if (key.match(/^node_modules\//)) {
        delete files[key];
      }
    }
    init.copyAndProcess(files, props);
    return done();
  });
};
