// Generated by CoffeeScript 1.5.0

exports.description = "Template for my Webkit-only pages";

exports.notes = "run `npm install` and `bower install`";

exports.warnOn = '*';

exports.template = function(grunt, init, done) {
  return init.process({}, [], function(err, props) {
    var files;
    files = init.filesToCopy(props);
    init.copyAndProcess(files, props);
    return done();
  });
};
